Создал README.md и TZ.md
kipar1s/control_vers pull request #28
Opened 2024-12-22 10:13 UTC by kipar1s

Создал файл README.md с описание проекта , участников, требований для запуска , планом на будущее и ссылкой на техническое задание , в котором описал основные компоненты приложения и функциональные требования,

2024-12-22 10:17 UTC, Halitdinoff approved these changes
все отлично

2024-12-22 10:18 UTC, DrowsyKatanka approved these changes
все хорошо

2024-12-23 06:58 UTC, Laggon requested changes
Нужно смержить изменения из основной ветки, т.к. данная ветка отстает и имеет конфликты

2024-12-24 07:47 UTC, Laggon requested changes
На данный момент в основной ветке должен быть только файл README.md и в нем только название проекта

Остальные изменения должны вноситься с помощью PR

После исправления основной ветки, нужно смержить изменения в данную ветку по [инструкции](https://github.com/Laggon/docs/blob/main/merge/index.md)

2024-12-25 13:35 UTC, Laggon requested changes
Отставание от основной ветки и конфликт все еще есть

2024-12-26 04:22 UTC, closed without merging